#ifndef REACTOR_REACTOR_DEFAULTDEMUXER_HEADER
#define REACTOR_REACTOR_DEFAULTDEMUXER_HEADER

#include <reactor/PollDemuxer.hh>

typedef PollDemuxer DefaultDemuxer;

#endif // REACTOR_REACTOR_DEFAULTDEMUXER_HEADER
